# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  release:
    types: [created] #not on push, since that will be a bit much

permissions:
  contents: write

jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
          
      - name: Install poetry
        run: pip install poetry
        
      - uses: actions/cache@v3
        name: Define a cache for the virtual environment based on the dependencies lock file
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}

      - name: ls
        run: dir

      - name: Install the project dependencies
        run: | 
         poetry install
        
      - name: Create Executable
        run: | 
          pip uninstall pillow
          pip install pillow
          pip install pyinstaller
          pyinstaller BeforeShutdown.spec
          
      # Zip build output
      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.5
        with:
         type: 'zip'
         filename: "BeforeShutdown-${{ github.ref_name }}.zip"
         path: 'dist'
 
      # Upload release asset
      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: BeforeShutdown-${{ github.ref_name }}.zip
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
